### ISSUE TITLE
Don't write dependencies to package.json

### ISSUE THREAD

**Issue by corywhite999** [xipcode/xipcode#11]
Putting the dependency array in the package.json makes a technically invalid package. After a xipcode user runs `gulp install`, running `npm install` throws an error because these xipcode-created packages are not in the npm registry.

**Comment by dougjanzen** [comment]
@corywhite999, I pushed directly to master by mistake.   It's a really simple change though so should be fine, but if you have any feedback let me know and I can do a PR.

**Comment by corywhite999** [comment]
No, looks good to me. Thanks a lot.

Cory
