### ISSUE TITLE
Get Github link to show up on npm page

### ISSUE THREAD

**Issue by corywhite999** [xipcode/xipcode#14]
I thought that updating the url in the package.json might do the trick, but it did not.

**Comment by dougjanzen** [comment]
See https://github.com/xipcode/xipcode/pull/16/commits/e0217360585be27080c01b2f70dedb0e7f0b3f9b

The repository field was being excluded since it used to be a non-public repository.

**Comment by corywhite999** [comment]
That fixed it, Doug.
